name: Docker-Hub-Autopublishing

on:
  push:
    tags:
      - '*'
      
jobs:
  build:
    runs-on: debian-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build docker image and push to docker hub
      run: |
        echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u michivonah --password-stdin
        docker image build -t michivonah/ep-alerts:latest .
        docker push michivonah/ep-alerts:latest
